### ISSUE TITLE
Install resulted in error

### ISSUE THREAD

**Issue by slaterjsharp** [IowaComputerGurus/DnnTelerikIdentifier#2]
Hi,

Firstly, thanks for this great tool! Can't wait to use it! Unfortunately I tried to install as a host and got errors. Used the download as zip from here at Github. Attaching screencap (somehow). It's a 248KB zip file, so can't be file size. No DNN error log. 
![image](https://user-images.githubusercontent.com/6339870/99592472-45698380-29be-11eb-9d66-fa38a9c2e7ba.png)

**Comment by mitchelsellers** [comment]
Can you check the /portals/_default/logs to see if there is a detailed error?

Typically if you have an issue there it is permissions based.

**Comment by slaterjsharp** [comment]
Troubleshot with Mitch. Somehow the download from Github got corrupted. Neither of us are sure how that happened. Considering my recent track record with other tech, we can probably chalk this up to a pebcak error.
