### ISSUE TITLE
DnnTelerikIdentifier locks all files in root/bin

### ISSUE THREAD

**Issue by Navilois** [IowaComputerGurus/DnnTelerikIdentifier#4]
I just used the module to check for Telerik dependencies. Two modules required an upgrade to the latest version (Feedback & Announcements).

The upgrades failed due to files being in use, took me a while to figure out. Seems like DnnTelerikIdentifier checks all DLLs in root/bin but doesn't release the file handle? All DLLs have been in use by w3wp.exe and only after recycling the IIS AppPool and NOT refreshing the page, which ran DnnTelerikIdentifier, allowed me to upgrade the modules.

**Comment by mitchelsellers** [comment]
We have noticed an issue that impacts some installations on this, we are trying to identify a fix

**Comment by Navilois** [comment]
This might be helpful:
https://stackoverflow.com/questions/1031431/system-reflection-assembly-loadfile-locks-file

**Comment by mitchelsellers** [comment]
Released version 1.0.2 with a fix!
