### ISSUE TITLE
Could not install v1.2 after 1.1 in place

### ISSUE THREAD

**Issue by moorecreative** [IowaComputerGurus/DnnTelerikIdentifier#6]
Within a DNN 9.5 instance where I had installed the earlier 1.1 version of the Identifier, I was not able to install the new 1.2 version.
- 1.1 was already installed
- attempted install of 1.2 version
- received error about not being able to replace element which was in use
- uninstalled module, deleting files
- attempted install of 1.2 version, but perhaps not everything was removed from the database because on the install action, received the following: 
Failure ExceptionSystem.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.ModuleDefinitions' with unique index 'IX_ModuleDefinitions'. The duplicate key value is (Telerik Identifier). The statement has been terminated.

**Comment by mitchelsellers** [comment]
@moorecreative looks like you did not get a clear uninstall, we need to make sure that you get those values cleaned.

**Comment by mitchelsellers** [comment]
CLosing this issue fo now, if this is an issue we can recreate we will look at additional changes.
