### ISSUE TITLE
couldnt install DNNTelerikIdentifier

### ISSUE THREAD

**Issue by barnsley7** [IowaComputerGurus/DnnTelerikIdentifier#7]
i got an error when trying to install the DnnTelerikIdentifier-main.zip extension.

"Zip file size is too large, check your IIS settings for max upload file size.
Missing resources in the zip file.
Invalid files in the package.
File extension is not .zip.
Check that you are logged in."

zip isn't large, i've installed larger sizes. 
missing resources / invalid files in zip - i've not done anything to it. 
it is a zip extension. 
I am logged in.

I am on DNN v 09.06.01

**Comment by mitchelsellers** [comment]
Are you sure that you downloaded the "Install" package from the releases section here?  this sounds like an error when trying to upload the entire source.

**Comment by barnsley7** [comment]
i'm not sure no. I was here: https://github.com/IowaComputerGurus/DnnTelerikIdentifier  and clicked on code >> download zip. It was called "DnnTelerikIdentifier-main.zip" and is 247kb.
is the install file on github?
thanks.

**Comment by mitchelsellers** [comment]
That is an incorrect file. You need to use the “install” file from the release. 

You can find it here https://github.com/IowaComputerGurus/DnnTelerikIdentifier/releases/tag/V1.0.2

**Comment by barnsley7** [comment]
thanks. I didn't know how to navigate to 'releases' (I still cannot see how to navigate to releases from the github site) so i'm thankful for the link.

**Comment by mitchelsellers** [comment]
No problem!

Releases are on the far right side on the main landing page of any GitHub repo.  (Or if on your phone they show at the bottom)
