### ISSUE TITLE
Unexpected errors on the report page

### ISSUE THREAD

**Issue by myElectrical** [IowaComputerGurus/DnnTelerikIdentifier#9]
Thanks for the tool Mitchel.

Have just installed on a DNN 9.10.2 site (just upgraded from 9.3.2) and while the tool identifies some Telerik affected dll, it also gives the following unexpected errors:

Microsoft.DiaSymReader.Native.amd64.dll (Could not load file or assembly '1495800 bytes loaded from IowaComputerGurus.Dnn.TelerikIdentifier, Version=1.0.0.38009, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.)

Microsoft.DiaSymReader.Native.x86.dll (Could not load file or assembly '1188080 bytes loaded from IowaComputerGurus.Dnn.TelerikIdentifier, Version=1.0.0.38009, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.)

**Comment by mitchelsellers** [comment]
Errors of this nature are expected, those are native assemblies and could not be loaded.  You can disregard them.

I'll try to adjust the error messaging in the future to try and call more attention to the things that can cause these types of errors.
